- Add prototypes in tests/wgrib2_test_util.c by including wgrib2_test_util.h, so compiler can check interfaces: wgrib2/tests/wgrib2_test_util.c:21:5: warning: no previous prototype for 'compare_files' [-Wmissing-prototypes]    21 | int compare_files(const char *fname1, const char *fname2) {       |     ^~~~~~~~~~~~~ wgrib2/tests/wgrib2_test_util.c:68:5: warning: no previous prototype for 'compare_grib2_files' [-Wmissing-prototypes]    68 | int compare_grib2_files(const char *fname1, const char *fname2) {       |     ^~~~~~~~~~~~~~~~~~~
- Fix resulting conflicting function declarations:
wgrib2/tests/wgrib2_test_util.c:23:5: error: conflicting types for 'compare_files'; have 'int(const char *, const char *)'
   23 | int compare_files(const char *fname1, const char *fname2) {
      |     ^~~~~~~~~~~~~
In file included from wgrib2/tests/wgrib2_test_util.c:12:
wgrib2/tests/wgrib2_test_util.h:9:5: note: previous declaration of 'compare_files' with type 'int(char *, char *)'
    9 | int compare_files(char *fname1, char *fname2);
      |     ^~~~~~~~~~~~~
wgrib2/tests/wgrib2_test_util.c:70:5: error: conflicting types for 'compare_grib2_files'; have 'int(const char *, const char *)'
   70 | int compare_grib2_files(const char *fname1, const char *fname2) {
      |     ^~~~~~~~~~~~~~~~~~~
wgrib2/tests/wgrib2_test_util.h:10:5: note: previous declaration of 'compare_grib2_files' with type 'int(char *, char *)'
   10 | int compare_grib2_files(char *fname1, char *fname2);
      |     ^~~~~~~~~~~~~~~~~~~

- Additionally, remove unused macro MAX_FILENAME_LEN.